export const items = [
  {
    id: "sofa",
    label: "Sofá",
  },
  {
    id: "mesa",
    label: "Mesa",
  },
  {
    id: "placainducción",
    label: "Placa induccón",
  },
  {
    id: "radiador",
    label: "Radiador",
  },
  {
    id: "nevera",
    label: "Nevera",
  },
  {
    id: "armario",
    label: "Armario",
  },
  {
    id: "colchon",
    label: "Colchón",
  },
  {
    id: "lavadora",
    label: "Lavadora",
  },
  {
    id: "microondas",
    label: "Microondas",
  },
  {
    id: "sillas",
    label: "Sillas",
  },
] as const;

export const provincesData = [
  { value: "Alaquàs" },
  { value: "Albal" },
  { value: "Albalat de la Ribera" },
  { value: "Alborache" },
  { value: "Alcàsser" },
  { value: "L'Alcúdia" },
  { value: "Aldaia" },
  { value: "Alfafar" },
  { value: "Alfarb" },
  { value: "Algemesí" },
  { value: "Alginet" },
  { value: "Almussafes" },
  { value: "Benetússer" },
  { value: "Benifaió" },
  { value: "Beniparrell" },
  { value: "Benicull de Xúquer" },
  { value: "Bétera" },
  { value: "Bugarra" },
  { value: "Bunol" },
  { value: "Camporrobles" },
  { value: "Carlet" },
  { value: "Catadau" },
  { value: "Catarroja" },
  { value: "Caudete de las Fuentes" },
  { value: "Corbera" },
  { value: "Quart de Poblet" },
  { value: "Cullera" },
  { value: "Chera" },
  { value: "Cheste" },
  { value: "Xirivella" },
  { value: "Chiva" },
  { value: "Favara" },
  { value: "Fortaleny" },
  { value: "Fuenterrobles" },
  { value: "Godelleta" },
  { value: "Guadassuar" },
  { value: "Llíria" },
  { value: "Loriguilla (solo núcleo urbano junto a la A-3)" },
  { value: "Llaurí" },
  { value: "Llombai" },
  { value: "Macastre" },
  { value: "Manises" },
  { value: "Massanassa" },
  { value: "Mislata" },
  { value: "Montserrat" },
  { value: "Montroi" },
  { value: "Paiporta" },
  { value: "Paterna" },
  { value: "Pedralba" },
  { value: "Picanya" },
  { value: "Picassent" },
  { value: "Polinyà de Xúquer" },
  { value: "Real" },
  { value: "Requena" },
  { value: "Riba-roja de Túria" },
  { value: "Riola" },
  { value: "Sedaví" },
  { value: "Siete Aguas" },
  { value: "Silla" },
  { value: "Sinarcas" },
  { value: "Sollana" },
  { value: "Sot de Chera" },
  { value: "Sueca" },
  { value: "Tavernes de la Valldigna" },
  { value: "Torrent" },
  { value: "Turís" },
  { value: "Utiel" },
  { value: "València (población de pedanías del sur)" },
  { value: "Yátova" },
  { value: "Benicull de Xúquer" },
  { value: "Llocnou de la Coron" },
];
